properties([
  disableConcurrentBuilds(),
  buildDiscarder(logRotator(numToKeepStr: '10', daysToKeepStr: '30'))
])

timeout(time: 1, unit: 'HOURS') {
  buildPod(context: 'ci', gpus: 1) {
    withEnv(["HOME=$WORKSPACE"]) {
        stage('Build') {
                sh 'uv sync -v --extra cuda'
        }
        stage('Test') {
                sh '''#!/bin/sh -e
                    export OMP_NUM_THREADS=$PARALLEL
                    uv run --extra cuda pytest -v
                '''
        }
        stage('Test with CUDA Sanitizer') {
                sh '''#!/bin/sh -e
                    export OMP_NUM_THREADS=$PARALLEL
                    uv sync --extra cuda
                    compute-sanitizer .venv/bin/python -m pytest -sv -k cufinufft --benchmark-skip
                '''
        }
    }
  }
}
